name: ci

on:
  push:
    branches: [ main, dev ]
    tags:
      - v*
  pull_request:

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Build
        run: msbuild Chanify.sln -p:Configuration=Release -p:Platform=x86
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Build
        run: |
          msbuild Chanify.sln -p:Configuration=Release -p:Platform=x86
          msbuild Chanify.sln -p:Configuration=Release -p:Platform=x64
          mkdir chanify_windows_i386
          cp Release\Chanify.exe .\chanify_windows_i386\
          cp LICENSE .\chanify_windows_i386\
          cp README.md .\chanify_windows_i386\
          powershell Compress-Archive -Path .\chanify_windows_i386\* -DestinationPath .\chanify_windows_i386.zip
          mkdir chanify_windows_x86_64
          cp x64\Release\Chanify.exe .\chanify_windows_x86_64\
          cp LICENSE .\chanify_windows_x86_64\
          cp README.md .\chanify_windows_x86_64\
          powershell Compress-Archive -Path .\chanify_windows_x86_64\* -DestinationPath .\chanify_windows_x86_64.zip
      - name: Run Releaser
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            chanify_windows_i386.zip
            chanify_windows_x86_64.zip
