name: ci

on:
  push:
    branches: [ main, dev ]
    tags:
      - v*
  pull_request:

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Build
        run: msbuild Chanify.sln -p:Configuration=Release -p:Platform=x86
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Build
        run: |
          msbuild Chanify.sln -p:Configuration=Release -p:Platform=x86
          cp Release/Chanify.exe ./Chanify.exe
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            README.md
            Chanify.exe
